### ISSUE TITLE
Getting "Error Reading Spreadsheet" error while reading a spreadsheet.

### ISSUE THREAD

**Issue by nidhiag** [jpillora/node-edit-google-spreadsheet#103]
I am using this node_module to read the spreadsheet in my application. 
Application is crashing badly frequently with the error "Error Reading Spreadsheet" . 
/app/node_modules/edit-google-spreadsheet/lib/spreadsheet.js:480:7\n    at Request._callback (/home/vcap/app/node_modules/edit-google-spreadsheet/lib/spreadsheet.js:105:14)\n    at self.callback (/home/vcap/app/node_modules/request/request.js:186:22)\n   

This is the log with the version 0.2.21 .

**Comment by apasrini** [comment]
@jpillora Any update on this issue? Even I am hitting this issue with this version 0.2.21.Any resolution would be of much help.

**Comment by apasrini** [comment]
Any response on this issue ?

**Comment by apasrini** [comment]
@jpillora @TimJohns @gnihi @gebrits @garaboncias @IvanGuardado @cybic  Can you please help out on this issue. Its quite urgent we need this to be resolved or please provide us a way out of this error.
Peeps, Please let me know if you need more details.

**Comment by apasrini** [comment]
I see now Error: worksheet 'Sheet1' not found, will this exception app seem to crash.

**Comment by IvanGuardado** [comment]
Hi @apasrini,

It's hard to help if you do not provide a code we can use to reproduce the error. Could you?
