### ISSUE TITLE
Can't read metadata

### ISSUE THREAD

**Issue by onlyurei** [jpillora/node-edit-google-spreadsheet#51]
Looks like the url to get the feed didn't get updated in metadata.js (updated in index.js), also the metadata object from Google now has different property names for updated, title, rowCount, and colCount.

These prevents successful updates to Google Spreadsheet using the module for me:

Logging into Google...
Logged into Google
Sending updates...
Determining worksheet size...

TypeError: Cannot read property 'updated' of undefined
    at Metadata.extract (/Users/ken/Projects/institution-webapp/scripts/node/localization/node_modules/edit-google-spreadsheet/lib/metadata.js:15:35)
    at /Users/ken/Projects/institution-webapp/scripts/node/localization/node_modules/edit-google-spreadsheet/lib/metadata.js:28:26
    at Request._callback (/Users/ken/Projects/institution-webapp/scripts/node/localization/node_modules/edit-google-spreadsheet/lib/index.js:125:12)
    at Request.self.callback (/Users/ken/Projects/institution-webapp/scripts/node/localization/node_modules/edit-google-spreadsheet/node_modules/request/index.js:148:22)
    at Request.emit (events.js:98:17)
    at Request.<anonymous> (/Users/ken/Projects/institution-webapp/scripts/node/localization/node_modules/edit-google-spreadsheet/node_modules/request/index.js:876:14)
    at Request.emit (events.js:117:20)
    at IncomingMessage.<anonymous> (/Users/ken/Projects/institution-webapp/scripts/node/localization/node_modules/edit-google-spreadsheet/node_modules/request/index.js:827:12)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:938:16

**Comment by jpillora** [comment]
Fixed by #44
