### ISSUE TITLE
Which version of Node works? Keep getting "Error: toString failed"

### ISSUE THREAD

**Issue by ericmuyser** [jpillora/node-edit-google-spreadsheet#89]
Hey guys,

So I ran into some memory issues running Node v0.10.26, so I've upgrade to v5.5.0. Now what I'm running into is a toString issue with buffers. Possibly a Node bug due to encoding. Do we know which version of Node is known to work?

> Uncaught exception:  [Error: toString failed] Error: toString failed
    at Buffer.toString (buffer.js:405:11)
    at BufferList.toString (/ude/bb/sites/brickbrotherhood.com/tools/falcon/node_modules/bl/bl.js:160:33)
    at Request.<anonymous> (/ude/bb/sites/brickbrotherhood.com/tools/falcon/node_modules/request/request.js:1013:32)
    at emitOne (events.js:95:20)
    at Request.emit (events.js:182:7)
    at IncomingMessage.<anonymous> (/ude/bb/sites/brickbrotherhood.com/tools/falcon/node_modules/request/request.js:962:12)
    at emitNone (events.js:85:20)
    at IncomingMessage.emit (events.js:179:7)
    at endReadableNT (_stream_readable.js:906:12)
    at nextTickCallbackWith2Args (node.js:474:9)
    at process._tickCallback (node.js:388:17)

If I invoke a stack trace in bl/bl.js to find out where it's being instantiated, I get this:

> at new BufferList (/ude/bb/sites/brickbrotherhood.com/tools/falcon/node_modules/bl/bl.js:7:13)
    at BufferList (/ude/bb/sites/brickbrotherhood.com/tools/falcon/node_modules/bl/bl.js:6:12)
    at Request.onRequestResponse (/ude/bb/sites/brickbrotherhood.com/tools/falcon/node_modules/google-auth-library/node_modules/request/request.js:1011:20)
    at emitOne (events.js:90:13)
    at ClientRequest.emit (events.js:182:7)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:425:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:88:23)
    at TLSSocket.socketOnData (_http_client.js:315:20)
    at emitOne (events.js:90:13)
    at TLSSocket.emit (events.js:182:7)
    at readableAddChunk (_stream_readable.js:147:16)
    at TLSSocket.Readable.push (_stream_readable.js:111:10)
    at TLSWrap.onread (net.js:523:20)

Seems to derive from `google-auth-library` creating BufferLists and probably trying to turn them into strings.

Ideas?

Cheers guys

**Comment by TimJohns** [comment]
Eric,

I'm actively using v0.12.7, and I've run on several versions of 4 as well, but if you can give me some guidance on reproducing it, I'll see if I can diagnose on v5.5.0 and see what I can do.

- Tim

**Comment by ericmuyser** [comment]
Hi @TimJohns!

It actually appears that this is due to an internal memory limit of 256mb when using toString() on Buffers (like requests or files). I'm working on re-compiling with a higher limit to verify and continue working. I suspect my spreadsheet has exceeded 256mb because it's about 11K lines with 30 columns. Some cells have JSON data. I wonder if I could change the google-auth-library so it doesnt try to convert the entire thing to a string at once to get around this problem.

An issue I found with some details on this: https://github.com/nodejs/node/issues/3175

Cheers

**Comment by TimJohns** [comment]
Thanks @ericmuyser 

I just ran the unit tests on 5.5 with no problem, although there isn't much to the tests yet, so that doesn't mean a lot. I also ran a quick check with some of my own code, though, and also no problem there.  

I'm not sure I'm reading that call stack correctly, but I don't see a reference to node-edit-google-spreadsheet in there?

**Comment by ericmuyser** [comment]
Hey @TimJohns 

Thanks for the response! I wrote a nice detailed comment a while back and my tab crashed, so I forgot about this. Lets just say I didn't solve the memory limit, and instead just removed some pretty heavy data from my spreadsheet.

As this is an issue with Node.js stream memory limits, I'm going to close this. Cheers!
